version: '3.8'

services:
  servicea:
    build: ./serviceA
    container_name: servicea
    ports:
      - "8081:8080"    # Optional: expose service A to host on port 8081
    networks:
      - app-network

  serviceb:
    build: ./serviceB
    container_name: serviceb
    ports:
      - "8082:8080"    # Optional: expose service B to host on port 8082
    networks:
      - app-network

  nginx:
    build: ./nginx       # Use this if you have a Dockerfile; otherwise, use: image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - servicea
      - serviceb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
