version: '3.8'

services:
  service1:
    build: ./service
    container_name: service1
    environment:
      - APP_NAME=Docker 1
    networks:
      - app-network

  service2:
    build: ./service
    container_name: service2
    environment:
      - APP_NAME=Docker 2
    networks:
      - app-network

  nginx:
    build: ./nginx       
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
